### ISSUE TITLE
What's included

### ISSUE THREAD

**Issue by eno812** [Swader/homestead_improved#10]
Hi,

I'm looking for information on what is included in this box? How can I check what's installed on this box?

**Comment by Swader** [comment]
- Ubuntu 16.04
- Git
- PHP 7.0
- HHVM
- Nginx
- MySQL
- MariaDB
- Sqlite3
- Postgres
- Composer
- Node (With PM2, Bower, Grunt, and Gulp)
- Redis
- Memcached
- Beanstalkd
