### ISSUE TITLE
Getting always nginx welcome page

### ISSUE THREAD

**Issue by RobertLangore** [Swader/homestead_improved#11]
Hi,

I configured all correctly but I'm geting always the nginx welcome page.

I tried this http://stackoverflow.com/questions/24274387/using-laravel-homestead-no-input-file-specified, but no luck (couldn't execute: homestead up --provision).

What is the problem? How can it be solved?

**Comment by Swader** [comment]
You're using the wrong package. This box has no "homestead" command, and is not intended to be used as such. Follow the instructions in this post to the letter, and it will work: [Homestead Improved](http://www.sitepoint.com/quick-tip-get-homestead-vagrant-vm-running/)
