### ISSUE TITLE
Not possible to change file access rights

### ISSUE THREAD

**Issue by sea2lion** [Swader/homestead_improved#13]
Hi,

I am using laravelcollective/remote and I have generated SSH keys to be used to connect to another machine. All works if I chose to connect using a password, but not when I try to use the ssh keys.
The problem is with Homestead, it doesn't allow me to change file rights. And apparently the rights are too loose for ssh connection to start:

`@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0555 for '/path/to/my/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
`

**Comment by Swader** [comment]
Hi,

>  it doesn't allow me to change file rights

Not sure what you mean by this. How does it not allow you?
