### ISSUE TITLE
Are you maintaining this?

### ISSUE THREAD

**Issue by COLABORATI** [Swader/homestead_improved#14]
I see that you forked that homestead project - but it looks like you are not maintaining it anymore - so was this just a one-time shot or do you expect this project to catch up with the original? 

what about participating in the original project, wouldn't that be a good idea?

**Comment by Swader** [comment]
It's being maintained and actively used by a lot of people. See [Homestead Improved](http://www.sitepoint.com/quick-tip-get-homestead-vagrant-vm-running/) - it's actually being used in every SitePoint tutorial as a starting point, not only in people's usual development environment.

The original also needs you to have PHP installed on the machine where you're powering up the VM, which is a big no-no for me.

I don't expect it to catch up to the original - instead, I'm just providing a simpler Homestead for my readers.
