### ISSUE TITLE
Vagrant up hangs forever on Windows 7

### ISSUE THREAD

**Issue by oussaka** [Swader/homestead_improved#20]
vagrant up stuck in this step!

vagrant 2.1.1
virtualbox 5.1.38
win 7

`` default: (Reading database ... 80%
    default: (Reading database ... 85%
    default: (Reading database ... 90%
    default: (Reading database ... 95%
    default: (Reading database ... 100%
    default: (Reading database ...
    default: 156264 files and directories currently installed.)
    default: Purging configuration files for mysql-common (5.8+1.0.4) ...
    default: Purging configuration files for mysql-server-5.7 (5.7.22-0ubuntu18.04.1) ...
    default: ☼
    default: Package configuration┌─────────────────────┤ Configuring mysql-server-5.7 ├──────────────────────┐│││ The /
var/lib/mysql directory which contains the MySQL databases is about  ││ to be removed.││││ This will also erase all data
 in /var/lib/mysql-files as well as││ /var/lib/mysql-keyring.││││ If you're removing the MySQL package in order to later
 install a more││ recent version or if a different mysql-server package is already using    ││ it, the data should be ke
pt.││││ Remove all MySQL databases?││││<Yes><No>☼│││└───────────────────────────────────────────────────────────────────
────────┘
``

**Comment by Swader** [comment]
I'm sorry, we can't support Windows 7, there's no way for me to test or debug on such an ancient system.
