### ISSUE TITLE
Even simpler?

### ISSUE THREAD

**Issue by TRPB** [Swader/homestead_improved#4]
If the aim of this project is to aid in simplicity wouldn't it be better to cut out a few of the steps?

Currently in order to see something working you need to:
- clone the repo
- amend the HOSTS file 
- Create the directory `Project/Public`
- Run `vagrant up`
- Write a file to `Project/Public`
- Navigate to `homestead.app/file.php`

They're simple steps but it's quite complicated for newcomers. Wouldn't it be better just to create a default page that is available on localhost:8080 with a nice Hello World message?

If this repo contained the file `Project/Public/index.html` and set to listen on `localhost:8080` the steps could be:
- clone the repo
- Run `vagrant up`
- Navigate to `localhost:8080/` and see the "Hello World ,it's working!" page.

If the goal is to quickly get people up and running, providing a default hello world and not requiring editing HOSTS would help reduce the number of steps and allow an even simpler start.

**Comment by Swader** [comment]
I agree with having a default file in there as a Hello World example, but not with the localhost:8080 stuff. I believe ports in URIs will confuse those not familiar with them, and overhead for those who are. Besides, to get it to respond to localhost, they still need to edit `hosts` to make sure the IP of the machine redirects to home.

However, with a simple Hello file already inside, people should be able to access it via 192.168.10.10 by default, as soon as vagrant up is done.

Would this help?
