### ISSUE TITLE
5.1

### ISSUE THREAD

**Issue by keithwhyman** [Swader/homestead_improved#5]
Does this work with 5.1 ?

**Comment by Swader** [comment]
Homestead has nothing to do with Laravel, except that it shares the brand
name. So it works with any framework, or without a framework. It's just a
virtual machine setup.


-- 
Bruno Skvorc
PHP editor, SitePoint.com
Devangelist, Diffbot.com

Twitter: @bitfalls <http://www.twitter.com/bitfalls>
G+: google.com/+BrunoSkvorc
Skype: bruno.skvorc

**Comment by keithwhyman** [comment]
oh sorry, misunderstanding my side
