### ISSUE TITLE
bad gateway error: php7.0-fpm.sock not working

### ISSUE THREAD

**Issue by robincrama** [Swader/homestead_improved#6]
After a clean install a bad gateway error is shown.
In the error log you will find this:

2016/02/04 15:33:47 [crit] 1634#0: *13 connect() to unix:/var/run/php/php7.0-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.10.1, server: homestead.app, request: "GET / HTTP/1.1", upstream: "$

My quickfix:
Change the fastcgi_pass item in the config file of the virtual host to:
fastcgi_pass unix:/var/run/php5-fpm.sock;

**Comment by Swader** [comment]
Your vagrant box is outdated. Run `vagrant box update` while in a homestead improved cloned folder and the problem will be solved.

Homestead Improved now uses PHP 7 by default, which is why your error appears (it's still using the old box but new configuration).

**Comment by robincrama** [comment]
Thank you,
Tried vagrant box update (updated correctly)

vagrant box update
==> default: Checking for updates to 'laravel/homestead'
    default: Latest installed version: 0.2.7
    default: Version constraints: >= 0
    default: Provider: virtualbox
==> default: Updating 'laravel/homestead' with provider 'virtualbox' from version
==> default: '0.2.7' to '0.4.1'...
==> default: Loading metadata for box 'https://atlas.hashicorp.com/laravel/homestead'
==> default: Adding box 'laravel/homestead' (v0.4.1) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/laravel/boxes/homestead/versions/0.4.1/providers/virtualbox.box
    default: Progress: 100% (Rate: 13.5M/s, Estimated time remaining: --:--:--)

 that still gives this error on provision:

==> default: php7.0-fpm: unrecognized service
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

And still gives the 502 Bad Gateway

**Comment by Swader** [comment]
An update won't automatically update the box you're in, counter-intuitively. You need to start a new box in order for this to work. Could you give that a go?

**Comment by robincrama** [comment]
Worked like a charm, txs for the hint. 
(deleted all homestead boxes and ran vagrant up)
